<?php

use ObjectivePHP\Application\View\Helper\Vars;
use Project\Entity\DB\Package;

?>
<style>
    .progress.active .progress-bar {
        -webkit-transition: none !important;
        transition: none !important;
    }
</style>
<div class="row">
    <div class="col-md-offset-2 col-md-8">

        <form id="createMachine">
            <div class="panel panel-primary">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Configuration</h4>
                    <div class="btn-group pull-right">
  <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" id="templateBtn" name="templateBtnName"><span id="selected">Template:Yes</span>
  <span class="caret"></span></button>
  <ul class="dropdown-menu" id="templatejson">
    <li><a href="#">Template:Yes</a></li>
    <li><a href="#">Template: No</a></li>
  </ul>
                        <a href="#expert" id="expertbtn" class="btn btn-default btn-sm" data-toggle="collapse">Expert</a>
                    </div>
                </div>
                <div class="panel-body">
                    <?php
                    if (!Vars::collection('host')->isEmpty()) {
                        $host = Vars::collection('host')->toArray();
                        $machine_template = Vars::collection('machine_template')->toArray();
                        if ($host['host_config'] === 'FIXED') {
                            echo "<label for='name'>Hostname: </label><input id='name' class='form-control' type='text' value=" . $machine_template["name"] . " disabled>";
                        } elseif ($host['host_config'] === 'CUSTOM') {
                            echo "<label for='name'>Hostname: </label><input id='name' class='form-control' name='host[name]' type='text' required autofocus>";
                        } elseif ($host['host_config'] === 'RANDOM') {
                            echo "<div class='alert alert-info'>The Hostname will created randomly.</div>";
                        } else {
                            throw new Exception('Check your openstack.local.php file');
                        }
                    }
                    ?>
                </div>
            </div>

            <div id="expert" class="collapse">
                <div id="pkgpanel" class="panel panel-default">
                    <div class="panel-heading"><a href="#pkgpanel" onClick="$(pkgbody).toggle();">Packages</a></div>
                    <div class="panel-body">
                        <div id="pkgbody" style="display: none;">
                            <label for="selectAllorNot">All: <input type="checkbox" id="selectAllorNot"/></label><br>

                            <select id="packages" name="packages[]" class="form-control" style="width: 100%"
                                    multiple="multiple">
                                <?php

                                Vars::collection('packages')->each(
                                    function (Package $package) {
                                        echo "<option value=" . $package->getName();
					if ($package->getIsDefault()) { 
						echo  " selected>";
					} else { echo " >"; }
					echo $package->getName() . "</option>";
                                    }
                                );

                                ?>
                            </select>
                        </div>
                    </div>
                </div>

                <div d="wspanel" class="panel panel-default">
                    <div class="panel-heading"><a href="#wspanel" onClick="$(wsbody).toggle();">Web Server</a></div>
                    <div class="panel-body">
                        <div id="wsbody" style="display: none;">
                            <ul class="nav nav-tabs" role="tablist" id="webserverTabs">
                                <li role="presentation" class="active"><a href="#apache" aria-controls="apache"
                                                                          role="tab"
                                                                          data-toggle="tab">Apache</a></li>
                                <li role="presentation"><a href="#ngnix" aria-controls="nginx" role="tab"
                                                           data-toggle="tab">NginX</a>
                                </li>
                            </ul>

                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="apache">
                                    <br>
                                    <label> Install Apache:
                                        <input type="checkbox" name="webserver[]" id="apacheCheckbox" class="checkbox" 
						<?php if (Vars::collection('default_install')["apache2"] == "true") { echo 'checked'; } ?>
					>
                                    </label>
                                    <br>
                                    <label> DocumentRoot:
                                        <input <?php if (Vars::collection('default_install')["apache2"] != "true") { echo 'disabled'; } ?> required type="text" class="form-control"
                                               id="apache_document_root">
                                    </label>
                                    <br>
                                    <label> User:
                                        <input <?php if (Vars::collection('default_install')["apache2"] != "true") { echo 'disabled'; } ?> required type="text" class="form-control" value="www-data"
                                               id="apache_owner_directory">
                                    </label>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="ngnix">
                                    <br>
                                    <label> Install Nginx:
                                        <input type="checkbox" name="webserver[]" id="nginxCheckbox" class="checkbox">
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div d="wspanel" class="panel panel-default">
                    <div class="panel-heading"><a href="#wspanel" onClick="$(languagesbody).toggle();">Languages</a></div>
                    <div class="panel-body">
                        <div id="languagesbody" style="display: none;">
                            <ul class="nav nav-tabs" role="tablist" id="languagesTabs">
                                <li role="presentation" class="active"><a href="#php" aria-controls="php"
                                                                          role="tab"
                                                                          data-toggle="tab">PHP</a></li>
                            </ul>

                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="php">
                                    <br>
                                    <label> Install PHP:
                                        <input type="checkbox" name="php[]" id="phpCheckbox" class="checkbox" <?php if (Vars::collection('default_install')["php"] == "true") { echo 'checked'; } ?>>
                                    </label>
                                    <br>
                                    <label> Select your version:
                                        <select required <?php if (Vars::collection('default_install')["php"] != "true") { echo 'disabled'; } ?> name="php_version" id="php_version">
                                            <option value="php7.0" selected>7.0</option>
                                            <option value="php5.6">5.6</option>
                                            <option value="php5.5">5.5</option>
                                        </select>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if (Vars::collection('monitoring')["enabled"] == "true") { ?>
                    <div id="monpanel" class="panel panel-default">
                        <div class="panel-heading"><a href="#monpanel" onClick="$(monbody).toggle();">Monitoring</a>
                        </div>
                        <div class="panel-body">
                            <div id="monbody" style="display: none;">
                                <ul class="nav nav-tabs" role="tablist" id="monitoringTabs">
                                    <?php $mon_active = 0; ?>
                                    <?php if (Vars::collection('monitoring')["alerting"] == "true") { ?>
                                        <li role="presentation" class="active"><a href="#alerting"
                                                                                  aria-controls="alerting" role="tab"
                                                                                  data-toggle="tab"><?php echo Vars::collection('monitoring')["alerting_type"]; ?></a>
                                        </li>
                                        <?php $mon_active = 1;
                                    } ?>
                                    <?php if (Vars::collection('monitoring')["monitoring"] == "true") { ?>
                                        <li role="presentation" <?php if (!$mon_active) {
                                            echo 'class="active"';
                                            $mon_active = 1;
                                        } ?>><a href="#monitoring" aria-controls="monitoring" role="tab"
                                                data-toggle="tab"><?php echo Vars::collection('monitoring')["monitoring_type"]; ?></a>
                                        </li>
                                    <?php } ?>
                                </ul>
                                <div class="tab-content">
                                    <?php $mon_active = 0; ?>
                                    <?php if (Vars::collection('monitoring')["alerting"] == "true") { ?>
                                        <div role="tabpanel" class="tab-pane active" id="alerting">
                                            <br>
                                            <label>
                                                Install <?php echo Vars::collection('monitoring')["alerting_type"]; ?>:
                                                <input type="checkbox" name="alerting" id="alertingCheckbox"
                                                       class="checkbox" checked>
                                            </label>
                                        </div>
                                        <?php $mon_active = 1;
                                    } ?>
                                    <?php if (Vars::collection('monitoring')["monitoring"] == "true") { ?>
                                        <div role="tabpanel" class="tab-pane <?php if (!$mon_active) {
                                            echo 'active';
                                            $mon_active = 1;
                                        } ?>" id="monitoring">
                                            <br>
                                            <label>
                                                Install <?php echo Vars::collection('monitoring')["monitoring_type"]; ?>
                                                :
                                                <input type="checkbox" name="monitoring" id="monitoringCheckbox"
                                                       class="checkbox" checked>
                                            </label>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>

                <div id="dbpanel" class="panel panel-default">
                    <div class="panel-heading"><a href="#dbpanel" onClick="$(dbbody).toggle();">Database</a></div>
                    <div class="panel-body">
                        <div id="dbbody" style="display: none;">
                            <ul class="nav nav-tabs" role="tablist" id="databaseTabs">
                                <li role="presentation" class="active"><a href="#mysql" aria-controls="mysql" role="tab"
                                                                          data-toggle="tab">MySQL</a></li>
                                <li role="presentation"><a href="#mongodb" aria-controls="mongodb" role="tab"
                                                           data-toggle="tab">MongoDB</a>
                                </li>
                            </ul>

                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="mysql">
                                    <br>
                                    <label> Install MySQL:
                                        <input type="checkbox" name="database[]" id="mysqlCheckbox" class="checkbox" <?php if (Vars::collection('default_install')["mysql"] == "true") { echo 'checked'; } ?>>
                                    </label>
                                    <br>
                                    <label> Root Password:
                                        <input <?php if (Vars::collection('default_install')["mysql"] != "true") { echo 'disabled'; } ?> required type="password" class="form-control"
                                               id="mysql_root_password">
                                    </label>
                                    <label> Database:
                                        <input <?php if (Vars::collection('default_install')["mysql"] != "true") { echo 'disabled'; } ?> required type="text" class="form-control" id="mysql_database">
                                    </label>
                                    <label> New User:
                                        <input <?php if (Vars::collection('default_install')["mysql"] != "true") { echo 'disabled'; } ?> required type="text" class="form-control" id="mysql_new_user">
                                    </label>
                                    <label> New User Password:
                                        <input <?php if (Vars::collection('default_install')["mysql"] != "true") { echo 'disabled'; } ?> required type="password" class="form-control"
                                               id="mysql_new_user_password">
                                    </label>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="mongodb">
                                    <br>
                                    <label> Install MongoDB:
                                        <input type="checkbox" name="database[]" id="mongodbCheckbox" class="checkbox">
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if (Vars::collection('dns_config')["enabled"] == "true") { ?>
                    <div id="dnspanel" class="panel panel-default">
                        <div class="panel-heading"><a href="#dnspanel" onClick="$(dnsbody).toggle();">Dns</a></div>
                        <div class="panel-body">
                            <div id="dnsbody" style="display: none;">

                                <label> Add Dns Entry to Ovh:
                                    <input type="checkbox" name="dns[]" id="dnsCheckbox"
                                           class="checkbox" <?php if (Vars::collection('dns_config')["checked"] == "true") {
                                        echo "checked";
                                    } ?>>
                                </label>
                                <br>
                                <label>Type:
                                    <select required id="dns_type" class="form-control">
                                        <option value="A" <?php if (Vars::collection('dns_config')["type"] == "A") {
                                            echo "selected";
                                        } ?>>A
                                        </option>
                                        <option value="AAAA" <?php if (Vars::collection('dns_config')["type"] == "AAAA") {
                                            echo "selected";
                                        } ?>>AAAA
                                        </option>
                                        <option value="CNAME" <?php if (Vars::collection('dns_config')["type"] == "CNAME") {
                                            echo "selected";
                                        } ?>>CNAME
                                        </option>
                                        <option value="DKIM" <?php if (Vars::collection('dns_config')["type"] == "DKIM") {
                                            echo "selected";
                                        } ?>>DKIM
                                        </option>
                                        <option value="LOC" <?php if (Vars::collection('dns_config')["type"] == "LOC") {
                                            echo "selected";
                                        } ?>>LOC
                                        </option>
                                        <option value="MX" <?php if (Vars::collection('dns_config')["type"] == "MX") {
                                            echo "selected";
                                        } ?>>MX
                                        </option>
                                        <option value="NAPTR" <?php if (Vars::collection('dns_config')["type"] == "NAPTR") {
                                            echo "selected";
                                        } ?>>NAPTR
                                        </option>
                                        <option value="NS" <?php if (Vars::collection('dns_config')["type"] == "NS") {
                                            echo "selected";
                                        } ?>>NS
                                        </option>
                                        <option value="PTR" <?php if (Vars::collection('dns_config')["type"] == "PTR") {
                                            echo "selected";
                                        } ?>>PTR
                                        </option>
                                        <option value="SPF" <?php if (Vars::collection('dns_config')["type"] == "SPF") {
                                            echo "selected";
                                        } ?>>SPF
                                        </option>
                                        <option value="SRV" <?php if (Vars::collection('dns_config')["type"] == "SRV") {
                                            echo "selected";
                                        } ?>>SRV
                                        </option>
                                        <option value="SSHFP" <?php if (Vars::collection('dns_config')["type"] == "SSHFP") {
                                            echo "selected";
                                        } ?>>SSHFP
                                        </option>
                                        <option value="TXT" <?php if (Vars::collection('dns_config')["type"] == "TXT") {
                                            echo "selected";
                                        } ?>>TXT
                                        </option>
                                    </select>
                                </label>
                                <br>
                                <label>Domain Name:
                                    <select required id="dns_domain_name" class="form-control">
					<?php $selected = "selected";
                                        foreach (Vars::collection('dns_config')["domain"] as $domain) { 
                                            	echo '<option value="' . $domain . '" ' . $selected . '>' . $domain; 
						$selected = "";
                                        	echo '</option>';
					} ?>
                                    </select>
                                </label>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>

            <br>
            <input class="btn btn-danger btn-block" type="submit" id="SendToAnsibleApi"
                   value="Create and install Machine">
        </form>

    </div>
</div>

<br><br>
<div id="outputcreation" class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading"><a href="#outputcreation" onClick="$(outputbody).toggle();">Output</a></div>
            <div class="panel-body">
                <div id="outputbody" style="display: none;">

                    <div id="progress" class="progress progress-striped">
                        <div id="progress-bar-animated" class="progress-bar progress-bar-striped" role="progressbar"
                                     aria-valuenow="0"
                                     aria-valuemin="0" aria-valuemax="100" style="width:0%;">
                        </div>
                        <div id="task" class="text-center" style="position:absolute; color: black; right: 0; left: 0;">Ready</div>
                    </div>
                    <div><pre><strong>Info:</strong>
      Name:   <span id="ProgressName">Not Available</span>
      IP:     <span id="ipaddress">0.0.0.0</span>
      Status: <span id="status">Not Available</span>
                    </pre></div>

                    <div><pre><strong>Log:</strong>
			            <div id="result"></div>
		    </pre></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/js/handler.js"></script>
<script src="/js/installMachine.js"></script>
