<?php

use ObjectivePHP\Application\View\Helper\Vars;

?>
<script src="/js/deleteMachine.js"></script>
<style>
.vertical-alignment-helper {
    display:table;
    height: 100%;
    margin: auto;
}</style>
<div class="modal fade" id="confirmDeleteModal">
	<div class="vertical-alignment-helper">
	<div class="modal-dialog" style="display: table-cell; vertical-align: middle;">
      		<div class="modal-content">
        		<div class="modal-header">
          			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          			<h4 class="modal-title">Confirm Delete</h4>
        		</div>
        		<div class="modal-body">
          			<div class="modal-group"><p class="text-center">Are you sure tou want to Delete machine ?</p></div>
        			<div class="modal-footer">
					<button type="button" class="btn btn-danger" data-dismiss="modal" id="confirmDeleteMachine">Yes</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">No</button></div>
      			</div>
    		</div>
	</div>
	</div>
</div>

<div class="row">
    <div class="col-md-offset-2 col-md-8">

		<form id="createMachine">
                <div class="panel panel-primary">
                        <div class="panel-heading">Hostname</div>
                        <div class="panel-body">
			<label for='name'>Hostname: </label><input id='nametodelete' class='form-control' name='host[name]' type='text' required>
			</div>
		</div>
		</form>

		<div align="right"><input id="deletebtn" type="button" data-toggle="modal" data-target="#confirmDeleteModal" class="btn btn-danger" value="Delete" disabled/></div><br>

               <div class="panel panel-default">
                        <div class="panel-heading"><a href="#outputcreation" onClick="$(outputbody).toggle();">Output</a></div>
                        <div class="panel-body"><div id="outputbody" style="display: none;">

        <h2>Process</h2>
        <div id="progress" class="progress progress-striped">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="70"
                 aria-valuemin="0" aria-valuemax="100" style="width: 0%;">0%
            </div>
        </div>
        <h2>Log</h2>
        <div id="result" class="jumbotron text-center pre-scrollable">

        </div>
        <h2>IP-Address</h2>
        <div id="ipaddress" class="jumbotron text-center">
</div></div></div>
        </div>
    </div>
</div>
