<?php

use ObjectivePHP\Application\View\Helper\Vars;

?>
<div class="row">
    <div class="col-md-offset-2 col-md-8">

               <div class="panel panel-default">
                        <div class="panel-heading"><a href="#outputcreation" onClick="$(outputbody).toggle();">Output</a></div>
                        <div class="panel-body"><div id="outputbody" style="display: none;">

        <h2>Process</h2>
        <div id="progress" class="progress progress-striped">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="70"
                 aria-valuemin="0" aria-valuemax="100" style="width: 0%;">0%
            </div>
        </div>
        <h2>Log</h2>
        <div id="result" class="jumbotron text-center pre-scrollable">

        </div>
        <h2>IP-Address</h2>
        <div id="ipaddress" class="jumbotron text-center">
</div></div></div>
        </div>
    </div>
</div>
