<?php

use ObjectivePHP\Application\View\Helper\Vars;
use Project\Entity\Package;

?>
<style>
    .progress.active .progress-bar {
        -webkit-transition: none !important;
        transition: none !important;
    }
</style>
<div class="row">
    <div class="col-md-offset-2 col-md-8">

        <form id="createMachine">
            <div class="panel panel-primary">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Configuration</h4>
                    <div class="btn-group pull-right">
  <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" id="templateBtn" name="templateBtnName"><span id="selected">Template:Yes</span>
  <span class="caret"></span></button>
  <ul class="dropdown-menu" id="templatejson">
    <li><a href="#">Template:Yes</a></li>
  </ul>
                    </div>
                </div>
                <div class="panel-body">
                       <label for='name'>Hostname: </label><input id='name' class='form-control' name='host[name]' type='text' required autofocus>
		
		<br><br><div id="deploypanel" class="panel panel-default">
                    <div class="panel-heading"><a href="#deploypanel" onClick="$(deploybody).toggle();">Projects</a></div>
                    <div class="panel-body">
                        <div id="deploybody">
                            <ul class="nav nav-tabs" role="tablist" id="deployTabs">
				<?php 	$apps = array("chat", "connect", "connect-admin", "logger", "audit","mailer", "translate", "payment", "filer","esm","chatapp");
					$active = "active";
					foreach($apps as $app) { 
						echo '<li role="presentation" class="'.$active.'"><a href="#'.$app.'" aria-controls="deploy"
                                                                          role="tab" data-toggle="tab">'.$app.'</a></li>';
					$active = "";
					}
				?>
                            </ul>

                            <div class="tab-content">
				<?php   $active = "active";
				foreach($apps as $app) {
                                echo '<div role="tabpanel" class="tab-pane '.$active.'" id="'.$app.'">
				    <br><div class="checkbox">
					<label><input type="checkbox" name="'.$app.'" id="'.$app.'Checkbox" class="checkbox" checked>
                                    	<b>Install '.$app.' Project</b></label><br><br>
                                    <label> Select your Branch:
                                        <select required name="'.$app.'_version" id="'.$app.'_branch" class="form-control">
                                            <option value="master" selected>master</option>
                                        </select>
                                    </label>
					</div>
                                </div>';
				$active = "";
				}
				?>
                            </div>
                        </div>
                    </div>
                </div>
            </div></div>

            <br>
            <input class="btn btn-danger btn-block" type="submit" id="SendToAnsibleApi"
                   value="Create and install Machine">
        </form>

    </div>
</div>

<br><br>
<div id="outputcreation" class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading"><a href="#outputcreation" onClick="$(outputbody).toggle();">Output</a></div>
            <div class="panel-body">
                <div id="outputbody" style="display: none;">

                    <div id="progress" class="progress progress-striped">
                        <div id="progress-bar-animated" class="progress-bar progress-bar-striped" role="progressbar"
                                     aria-valuenow="0"
                                     aria-valuemin="0" aria-valuemax="100" style="width:0%;">
                        </div>
                        <div id="task" class="text-center" style="position:absolute; color: black; right: 0; left: 0;">Ready</div>
                    </div>
                    <div><pre><strong>Info:</strong>
      Name:   <span id="ProgressName">Not Available</span>
      IP:     <span id="ipaddress">0.0.0.0</span>
      Status: <span id="status">Not Available</span>
                    </pre></div>

                    <div><pre><strong>Log:</strong>
			            <div id="result"></div>
		    </pre></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/js/handler.js"></script>
<script src="/js/installMachine.js"></script>
