
<script type="text/javascript">
    $(document).ready(function(){
        $("#myTab li a").tab('show');
    });
</script>

<div class="row">
    <div class="col-md-offset-3 col-md-6">

    <form id="installServer" action="/post_data" method="post">
        <h3>Which server packages do you want to install?</h3>
        <input type="checkbox" id="selectAllorNot" /> <label for="selectAllorNot">Select All</label>
        <select multiple="multiple" name="serverpackages[]" id="serverpackages" style="width: 100%">
            <option value="postfix">postfix</option>
            <option value="munin-node">munin-node</option>
        </select>
        <br><br>
        <h3>Do you need a Webserver?</h3>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist" id="myTabs">
            <li role="presentation" class="active"><a href="#apache" aria-controls="apache" role="tab" data-toggle="tab">Apache</a></li>
            <li role="presentation"><a href="#ngnix" aria-controls="nginx" role="tab" data-toggle="tab">NginX</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="apache">
                apache
            </div>
            <div role="tabpanel" class="tab-pane" id="ngnix">
                nginx
            </div>
        </div>

        <br><br>
        <input type="submit" id="SendToAnsibleApi" value="Create Machine">
    </form>

</div>

</div>

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <h2>Result</h2>
        <div id="result" class="jumbotron text-center">
            <img src="/img/page-loader.gif" id="loading" />
        </div>
    </div>
</div>