<?php

use ObjectivePHP\Application\View\Helper\Vars;

?>
<script>
function listMachine() {
    let machines = [];

    $.ajax({
        type: 'GET',
        url: 'PlayBook',
        data: {
            playbook: 'getAllMachine'
        }
    })
    .done(function () {

    })
    .fail(function (error) {
        console.log(JSON.stringify(error));
    })

};
</script>
<div class="container">
<div align="right"><input type="button" class="btn btn-danger" value="Refresh" onclick="listMachine();"/></div>
<?php
                    if (!Vars::collection('hosts')->isEmpty()) {
                        $hosts = Vars::collection('hosts')->toArray(); ?>
			<div class="table-responsive"><table class="table table-hover">
			<thead>
      				<tr>
        				<th>Id</th>
        				<th>Name</th>
        				<th>Ip</th>
					<th>Location</th>
					<th>Status</th>
      				</tr>
    			</thead>
    			<tbody>			
			<?php foreach ( $hosts as $host) {
				if ($host->getStatus() != 'ACTIVE') { 
					$trclass = 'class="danger"';
				 }
				echo '<tr '. $class . '><td>' . $host->getid() . '</td><td>' . $host->getname() . '</td><td>' . $host->getip() . '</td><td>' . $host->getLocation() . '</td><td>' . $host->getStatus() . '</td></tr>';
			} ?>
			</tbody></table></div><?php
                    }
 ?>
<div>
