<?php

use ObjectivePHP\Application\View\Helper\Vars;

?>
<script>
function listMachine() {
    let machines = [];

    $.ajax({
        type: 'GET',
        url: 'PlayBook',
        data: {
            playbook: 'getAllMachine'
        }
    })
    .done(function () {

    })
    .fail(function (error) {
        console.log(JSON.stringify(error));
    })

};
</script>
<div class="container">
<div align="right"><input type="button" class="btn btn-default" value="Refresh" onclick="listMachine();"/></div>
<?php
                    if (!Vars::collection('hosts')->isEmpty()) {
                        $hosts = Vars::collection('hosts')->toArray(); ?>
			<table class="table">
			<thead>
      				<tr>
        				<th>Id</th>
        				<th>Name</th>
        				<th>Ip</th>
      				</tr>
    			</thead>
    			<tbody>			
			<?php foreach ( $hosts as $host) {
				echo '<tr><td>' . $host->getid() . '</td><td>' . $host->getname() . '</td><td>' . $host->getip() . '</td></tr>';
			} ?>
			</tbody></table><?php
                    }
 ?>
<div>
