<!-- Fixed navbar -->
<?php
use ObjectivePHP\Application\Config\ApplicationName;
use ObjectivePHP\Application\View\Helper\Vars;

$app = $this->getApplication();
$user = $app->getServicesFactory()->get('connect.client')->getUser()->toArray();

?>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://github.com/skrijeljhasib/AnsibleWeb"><?=

                Vars::$config->get(ApplicationName::class) ?>
            </a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
		<?php if (($user["current_role"]) == 'ADMIN') { ?>
                <li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Create <span class="caret"></span></a>
                <ul class="dropdown-menu">
			<li><a href="/deployMachine">Simple</a></li>
			<li><a href="/createMachine">Expert</a></li>
		</ul>
		</li>
		<?php } ?>
                <li><a href="/listMachine"> List </a></li>

            </ul>
	    <div class="navbar-right">
                    <?php
                    if (!empty($user['mini_avatar_url'])) {
                        echo '<img src="'.htmlspecialchars($user['mini_avatar_url'], ENT_QUOTES).'" alt="User avatar" style="max-height: 30px; position: absolute; top: -5px; left: -40px;" /></a>';
                    }
                    ?>
                    Hello, <?= htmlspecialchars($user['user_name'], ENT_QUOTES|ENT_SUBSTITUTE) ?>
                <ul class="nav navbar-nav">
                    <li>
                        <span class="imageAvatar"></span>
                        <?php if (null !== $user['mini_avatar_url']): ?>
                            <script>
                                var img = new Image();
                                img.onload = function () {
                                    document.getElementsByClassName('imageAvatar')[0].appendChild(img);
                                };
                                img.style.maxHeight = '30px';
                                img.style.top = '15px';
                                img.style.left = '-40px';
                                img.style.position= 'absolute';
                                img.src = '<?= $user['mini_avatar_url']; ?>';
                            </script>
                        <?php endif; ?>
                        <a href="/logout"><i class="glyphicon glyphicon-log-out"></i> Logout</a>
                    </li>
                </ul>
            </div>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
